---
title: "Communications"
output: 
  distill::distill_article:
    toc: true
    toc_float: true
    toc_depth: 2
    collapsed: true
    self_contained: false
    code_folding: false
    css:
      - css/GlobalTheme.css
---

<!-- TOC JAVASCRIPT ELEMENTS - code from the "A poor man’s TOC in {distill}" page -->
<!-- https://distillery.rbind.io/posts/2022-01-24-the-toc-in-distill/?panelset1=css-elements2&panelset2=javascript-elements2&panelset=yaml-output -->

<script>
function toggle () {
  document.getElementById("TOC").classList.toggle("hide");
};

window.addEventListener('DOMContentLoaded', () => {

  const observer = new IntersectionObserver(entries => {
    entries.forEach(entry => {
      const id = entry.target.getAttribute('id');
      if (entry.intersectionRatio > 0) {
        document.querySelector(`[href="#${id}"]`).parentElement.classList.add('active');
      } else {
        document.querySelector(`[href="#${id}"]`).parentElement.classList.remove('active');
      }
    });
  });

  // Track all headings that have an `id` applied
  document.querySelectorAll('h1[id], h2[id], h3[id], h4[id], h5[id], h6[id]').forEach((h1, h2, h3, h4, h5, h6) => {
    observer.observe(h1, h2, h3, h4, h5, h6);
  });
  
});
</script>

<!-- TOC JAVASCRIPT ELEMENTS END -->

<p class="small-text"><span>&#42;</span> indicate the person who presented the work.</p>

# Oral communications

## 2021
`r fontawesome::fa("square-caret-right", fill = "#333333")` &ensp; <strong>Q Petitjean</strong>*, Variable responses to multiple stressors in a wild freshwater fish: Gobio occitaniae. Oral communication at the <a href='https://www.biologie.uni-hamburg.de/en/forschung/grk2530/'>Department of Biology of the university of Hamburg (RTG 2530).</a> 

## 2019
`r fontawesome::fa("square-caret-right", fill = "#333333")` &ensp; <strong>Q Petitjean</strong>*, L Jacquin, L Riem, E Rojas, A Perrault, M Cousseau, P Laffaille, S Jean, Variability of responses to multiples stressors in fish: biological level and population matter. Oral communication at the <a href='https://helsinki.setac.org/welcome/'>SETAC Europe 29<sup>th</sup> meeting 2019.</a>

## 2018
`r fontawesome::fa("square-caret-right", fill = "#333333")` &ensp; <strong>Q Petitjean</strong>*, L Jacquin,  L Riem, E Rojas, A Perrault, M Cousseau, P Laffaille, S Jean, Variability of fish population responses to combined contamination and immune stressors in wild gudgeon. Oral communication at the <a href='https://sfecologie2018.sciencesconf.org/'>SFE² meeting 2018.</a>

## 2017
`r fontawesome::fa("square-caret-right", fill = "#333333")` &ensp; <strong>Q Petitjean</strong>*, J Côte, S Jean, A Perrault, O Morrisseau, P Laffaille, L Jacquin, Responses of freshwater fish to multiple stressors. Oral communication at the <a href='https://www.freshwatersciences.eu/effs/index.asp?page=SEFS&Id=4'>SEFS meeting 2017.</a>

## 2016
`r fontawesome::fa("square-caret-right", fill = "#333333")` &ensp; <strong>Q Petitjean</strong>*, A-V Walter-Simonnet, F Choulet, A-L Mariet, P Goncalves, H Laurent, P Rosenthal, A de Vaufleury, F Gimbert, From iron ore to ecotoxicological impacts: One thousand years of manganese history. Oral communication at the <a href='https://ichmet2016.ugent.be/'>ICHMET meeting 2016.</a>

<br/>

# Poster presentations

## 2019
`r fontawesome::fa("square-caret-right", fill = "#333333")` &ensp; M Pitout*, <strong>Q Petitjean</strong>, A Perrault, M Cousseau, P Laffaille, L Jacquin, S Jean, Physiological and transcriptomic responses to metal contamination and immune challenge in gudgeon. Poster presentation at the <a href='https://eb2019.sciencesconf.org/'>E&B meeting 2019.</a>

## 2018
`r fontawesome::fa("square-caret-right", fill = "#333333")` &ensp; <strong>Q Petitjean</strong>*, S Jean, J Côte, A Lamarins, A Perrault, P Laffaille, L Jacquin, Responses to combined temperature and immune stressors in wild gudgeon. Poster presentation at the <a href='https://sfecologie2018.sciencesconf.org/'>SFE² meeting 2018.</a>

## 2017
`r fontawesome::fa("square-caret-right", fill = "#333333")` &ensp; <strong>Q Petitjean</strong>*, J Côte, L Jacquin, A Perrault, O Morrisseau, P Laffaille, S Jean, Responses of freshwater fish to multiple stressors. Poster presentation at the FEE meeting 2017.

## 2016
`r fontawesome::fa("square-caret-right", fill = "#333333")` &ensp; <strong>Q Petitjean</strong>*, A-V Walter-Simonnet, F Choulet, A-L Mariet, P Goncalves, H Laurent, P Rosenthal, A de Vaufleury, F Gimbert, Impacts de la pr&eacute;sence de d&eacute;chets sid&eacute;rurgiques anciens sur la contamination des sols en m&eacute;taux. Poster presentation at the <a href='https://asso-sefa.fr/colloque-de-la-sefa'>French SEFA meeting 2016.</a>
